import './globals.css';
import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import NavBar from '@/components/layouts/navBar';
import ChildrenWrapper from '@/components/layouts/childWrapper';

const nunitoSans = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${nunitoSans.className} flex flex-col h-screen m-auto`}>
        <NavBar />
        <ChildrenWrapper>{children}</ChildrenWrapper>
      </body>
    </html>
  );
}
